curl -X POST \
  http://waiting.barattson.com/api/Security/post/auth/user \
  -H 'Accept: */*' \
  -H 'Content-Type: application/json' \
  -H 'Host: waiting.barattson.com' \
  -H 'cache-control: no-cache' \
  -d '{
  "UserName": "ilkinlikus@gmail.com",
  "Password": "P@ssw0rd_"
}